name: Build-Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Bump Version
        uses: opspresso/action-builder@v0.1.12
        with:
          args: --version

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Run Build
        run: |
          # npm run lint
          npm run build

      - name: Release to GitHub
        uses: opspresso/action-builder@v0.1.12
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push to Docker Hub
        uses: opspresso/action-builder@v0.1.12
        with:
          args: --docker
        env:
          # USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          LATEST: "true"

      - name: Build & Push to GitHub Package
        uses: opspresso/action-builder@v0.1.12
        with:
          args: --docker
        env:
          # USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISRTY: "docker.pkg.github.com"
          LATEST: "true"

      - name: Build & Push to AWS ECR
        uses: opspresso/action-builder@v0.1.12
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          LATEST: "true"
